### PR TITLE
Update measurement count in Kalman-Updater.

### PR DESCRIPTION
**Pull request by skasperski**
Required to filter patches using their measurement count.

### CODE REVIEW

**Comment by chhtz** [comment]
I'd recommend updating this in all cases where patches are merged (e.g., also when the result is a vertical). Perhaps just move this before the ``return true;`` in line 356.

**Comment by skasperski** [comment]
Thought about that, but there is another return there when one patch encloses the other one. And I think in that case the number of measurements should also be summed up.

**Comment by chhtz** [comment]
I think that is the case where a negative patch overwrites a positive patch, so it would make sense not to increase the weight here.

**Comment by saarnold** [comment]
The n is not part of the original MLS description, that is why it is not used in the mergeMLS method.
However I don't see a problem of using it there too.
But please increase it, like @chhtz suggested, for all the cases when two patches are merged. Line 355 before the methods returns true would be the correct place I think.

**Pull request merged**
